version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: postgres-pgvector
    environment:
      POSTGRES_DB: productos_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d productos_db"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  postgres_data: